name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Show yarn version
        run: yarn --version
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v6
      - name: Set up JDK
        uses: olafurpg/setup-scala@v12
        with:
          java-version: adopt@1.11 
      - name: Run compile
        run: sbt scalafmtCheckAll facade/compile facade/test facade/fullOptJS::webpack